server:
  port: ${PORT:8888}
  
spring:
  profiles:
    active:
    - ${profile:sys}
  application:
    name: airkerala-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SubinBMathew95/AirKerala-Config.git
          ignore-local-ssh-settings: true
          username: SubinBMathew95
          password: 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
          default-label: development
          clone-on-start: true
          search-paths:
            - airkerala-passengerservice

management:
  endpoints:
    web:
      exposure:
        include: health,info
       

